spring:
  application:
    name: order-service

server:
  port: 8085

credential:
  username: admin
  password: admin

secretKey: "I Love Java and Spring Boot. Spring Framework is one of the important, lightweight and easy to use Java Framework, which help us to simplify the Java application development. It provides Inversion of Control, Dependency Injection and strong infrastructure to develop simple and modular application"
expirationTime:  3600000
 #   follow : https://medium.com/@tericcabrel/implement-jwt-authentication-in-a-spring-boot-3-application-5839e4fd8fac

# http://localhost:8084/swagger-ui/index.html

# swagger

