spring:
  application:
    name: spring-learning
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8090/h2-console/
  datasource:
    url: jdbc:h2:mem:learningdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8090

# http://localhost:8090/swagger-ui/index.html

# swagger

